name: False Positive Report
description: Create a report to suggest a false positive.
title: "example.com"
labels:
  - "false positive"
  - "verification"
projects:
  - Phishing-Database/2
body:
  - type: markdown
    attributes:
      value: |+
        Thank you for reporting a false positive!

        We know this can be frustrating and confusing for webmasters, developers, and website owners. Please be patient; one of our team members will look into your issue as soon as possible. 

        To help us understand the problem, please provide clear and accurate information without unnecessary details. Keep your responses short and to the point. Our team knows what information they need, and they will ask for more if necessary.

        ### Important Notes:
        - **Title**: Please enter your domain name or IP only.
        - **One Issue per Domain**: Only report one issue per domain. If you have multiple issues, please use the comments section to refer to them instead of repeating everything.
        - **Basic Information Only**: When filling in the text boxes, do not include protocols like `https`. This applies to:
          - Domain
          - URIs
          - IP addresses and ranges (use CIDR notation, e.g., `192.0.2.0` or `192.0.2.0/24`)
        - **Comments**: Add any comments in the "Please explain why you believe this is a false positive" section only.
        - **Discovery**: "How did you discover this false positive?" is optional but appreciated.
        - **Review Requests**: If you have asked for a review from other sources, just mention who it was, without a long explanation. We will ask for more details if needed.

        If you have any questions or need assistance, please ask in our [Discussions](https://github.com/Phishing-Database/dev-center/discussions) section.

        Thank you,  
        The Phishing Database Project Team.

  - type: textarea
    id: subjects_domain
    attributes:
      label: What are the subjects of the false-positive domain
      description: |
        Please list the domains that you believe are false-positives.

        Please warn with "NSFW" where applicable.
      placeholder: |
        example.com
      render: Text
    validations:
      required: true


  - type: textarea
    id: subjects_uri
    attributes:
      label: What are the subjects of the false-positive URLs
      description: |
        Please list any URLs that you believe are false-positives.

        Please warn with "NSFW" where applicable.
      placeholder: |
        https://example.com/page
        https://sub.example.com/page
      render: Text
    validations:
      required: true


  - type: textarea
    id: subjects_ip
    attributes:
      label: What are the subjects of the false-positive IP
      description: |
        Please list IPs that you believe are false-positives.

        Please warn with "NSFW" where applicable.
      placeholder: |
        192.0.2.0/24
      render: Text
    validations:
      required: true

  - type: textarea
    id: info
    attributes:
      label: Why do you believe this is a false-positive?
      description: Please explain why you believe this is a false-positive.
      placeholder: |
        I believe this is a false-positive because...
    validations:
      required: true
  - type: dropdown
    id: discovery
    attributes:
      label: How did you discover this false-positive(s)?
      description: Please provide any information that may help us understand how you discovered this false-positive(s).
      multiple: true
      options:
        - VirusTotal
        - Phishtank
        - OpenPhish
        - Website was hacked
        - Other (Please fill out the next box)
    validations:
      required: true

  - type: textarea
    id: discovery_other
    attributes:
      label: Where did you find this false-positive if not listed above?
      description: Please provide any information that may help us understand how you discovered this false-positive(s).
      placeholder: |
        I discovered this false-positive by...
    validations:
      required: true

  - type: textarea
    id: peer_sources_review
    attributes:
      label: Have you requested a review from other sources?
      description: |
        Please only name who you have requested from.
      placeholder: |
        I have requested a review from...
    validations:
      required: false

  - type: textarea
    id: screenshot
    attributes:
      label: Do you have a screenshot?
      description: |
        If applicable to the problem, please provide some screenshots to help explain the problem.

        Please note that there need to be at least one blank line, separating before and after the image line.
        To add an image, use the following code: `![Screenshot of False Positive](https://example.com/path/to/image.png)`

        If you do not apply a screenshot, please consider deleting the lines in this box.
      value: |
        <details><summary>Screenshot</summary>


        </details>
    validations:
      required: false
