name: False Positive
title: 'YOUR_DOMAIN'
description: |
  Reporting of any false positives or domains that need to be whitelisted
labels:
  - 'false positive'
assignees:
  - mitchellkrogza
  - funilrys
projects: ["https://github.com/orgs/Phishing-Database/projects/2"]

body:
  - type: markdown
    attributes:
      value: '## Domains or links'
  - type: markdown
    attributes:
      value: |
        Please list any domains and links listed here which you believe are a false positive.

  - type: dropdown
    id: source
    attributes:
      label: More Information
      multiple: true
      description: |
        How did you discover your web site or domain was listed here?
      options:
        - Website was hacked
        - Phishtank
        - OpenPhish
        - VirusTotal
        - Other
      default: 0
    validations:
      required: true

  - type: textarea
    id: ifOther
    attributes:
      label: If other
      description: Please tell us where you have requested whitelisting from
      placeholder: |
        1. Mitchell Krogza - Phishing https://github.com/Phishing-Database/phishing/issues/$ID
        2. My Privacy DNS https://kb.mypdns.org/issue/MTX-$ID
        3. EasyList https://github.com/easylist/easylist/issues/$ID
      render: Text

  - type: textarea
    id: removal
    validations:
      required: true
    attributes:
      label: Have you requested removal from other blacklists?
      description: |
        Please include all relevant links, to any removals / whitelisting requests.
      placeholder: |
        I was marked as phishing at Project XYZ where I have requested to be unlisted via issue `https://examle.net/issue/$ID`
      render: Text

  - type: textarea
    id: actions
    attributes:
      label: Actions you have taken to fix your domain
      description: |
        Describe what actions and precaution you have done to remove and safeguarding your server against further attack.

        This descriptions should be in headline style to avoid give to much to information to the attacker.
      placeholder: |
        - I have deleted infected files
        - Updated the code as we found the bug
        - I did nothing and hoping this won't happen again, just like that
        - Deleted the scripts in the folder and changed the folder permission (chmod) + changes user ownership (chown)
      render: Markdown
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      placeholder: |
        Add any additional text about the problem and solutions here.
      render: Text

  - type: checkboxes
    id: todo
    attributes:
      label: 'I confirm that i have:'
      description: |
        Before you commit this issue, you have to be sure you have done the following things
      options:
        - label: I have deleted any, to me known, phishing content.
          required: true
        - label: I have to the best of my knowledge and resources, protected my server against repetition of this problem
          required: true
        - label: Read and understood [CONTRIBUTING](https://github.com/spirillen/ITT/blob/master/CONTRIBUTING.md#false-positives)
          required: true
        - label: I accept, if I deliberately gives false information, I risk never to be removed from this or any other blacklist(s).
          required: true
